version: "3.9"
services:
  database:
    image: "postgres:13-alpine"
    restart: on-failure
    environment:
      - "POSTGRES_USER=gamemaster"
      - "POSTGRES_PASSWORD=SuperSecretPassword"
      - "POSTGRES_DB=febang"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - "./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
      - "./db/postgres:/var/lib/postgresql/data"
    networks:
      - api_database

  # api_go:
  #   build: ./api_go
  #   restart: on-failure
  #   depends_on:
  #     - database
  #   networks:
  #     - api_database
  #     - nginx_api

  frontend_react:
    build: ./frontend_react
    volumes:
      - "./frontend_react/src:/app/src"
      - "./frontend_react/public:/app/public"
    # depends_on:
      # - api_go
    networks:
      - nginx_frontend

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - "./nginx/src/:/etc/nginx/src/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/ssl/:/etc/ssl/"
      - "./nginx/mime.type:/etc/nginx/mime.type"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_frontend
      - nginx_api
    depends_on:
      - database
      # - api_go
      - frontend_react


networks:
  nginx_frontend:
    driver: bridge
  nginx_api:
    driver: bridge
  api_database:
    driver: bridge
