CREATE TABLE "users" (
	"id" SERIAL,
	"name" VARCHAR(100) NOT NULL DEFAULT 'DefaultName',
	"updates" JSON NOT NULL DEFAULT '[]',
	"current_game" INT NOT NULL DEFAULT -1,
	"game_history" JSON NOT NULL DEFAULT '[]',
	"password" VARCHAR(64) NOT NULL DEFAULT ''
);

CREATE TABLE "games" (
	"id" SERIAL,
	"users" JSON NOT NULL DEFAULT '[]',
	"current_move_number" INT NOT NULL DEFAULT -1,
	"start_time" INT NOT NULL DEFAULT -1,
	"end_time" INT NOT NULL DEFAULT -1,
	"moves" JSON NOT NULL DEFAULT '[]',
	"current_status" JSON NOT NULL DEFAULT '{}'
);

CREATE TABLE "requests_log" (
	"id" SERIAL,
	"time" INT NOT NULL DEFAULT -1,
	"method" VARCHAR(10) NOT NULL DEFAULT 'NULL',
	"GET" JSON NOT NULL DEFAULT '{}',
	"POST" JSON NOT NULL DEFAULT '{}',
	"FILES" JSON NOT NULL DEFAULT '{}',
	"path" VARCHAR(100) NOT NULL DEFAULT 'NULL',
	"answer" VARCHAR(1000) NOT NULL DEFAULT 'NULL',
	"container" VARCHAR(10) NOT NULL DEFAULT 'NULL'
);

CREATE USER api WITH PASSWORD '9f5ad1c6-d027-4e99-8282-4c8eff292b4c';
GRANT ALL PRIVILEGES ON DATABASE "febang" TO api;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO api;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO api;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO api;